import type { MusicData } from "@/lib/music-api";

export const musicData: MusicData[] = [
  { title: "BBW", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "Call Out My Name", author: "The Weeknd", type: "single", album: "My Dear Melancholy," },
  { title: "GEMINI SEASON", author: "Kanye West", type: "single" },
  { title: "Drop The Lo", author: "Bryson Tiller", type: "single" },
  { title: "Cinderella (feat. Ty Dolla $ign)", author: "Mac Miller", type: "single", album: "The Divine Feminine" },
  { title: "U My Everything", author: "Sexyy Red & Drake", type: "single", album: "In Sexyy We Trust" },
  { title: "HIGHJACK (feat. Jessica Pratt)", author: "A$AP Rocky", type: "single" },
  { title: "Favorite (feat. Jeremih)", author: "Nicki Minaj", type: "single", album: "The Pinkprint (Deluxe)" },
  { title: "Cece's Interlude", author: "Drake", type: "single", album: "Thank Me Later" },
  { title: "Like a Tattoo", author: "Sade", type: "single", album: "Love Deluxe" },
  { title: "Cheetah Print", author: "Drake & Sexyy Red", type: "single", album: "MAID OF HONOUR" },
  { title: "Q&A", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "Un-thinkable (I'm Ready) [Remix] {feat. Drake}", author: "Alicia Keys", type: "single" },
  { title: "Don’t Worry", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Princess", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "6PM In New York", author: "Drake", type: "single", album: "If You're Reading This It's Too Late" },
  { title: "Road Trips", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "National Treasures", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Return of the Mack", author: "Mark Morrison", type: "single" },
  { title: "Janice STFU", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Burning Bridges", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "New Bestie", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "WNBA", author: "Drake", type: "single", album: "HABIBTI" },
  { title: "Gen 5", author: "Drake", type: "single", album: "HABIBTI" },
  { title: "Hoe Phase", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "Little Birdie", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Whisper My Name", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "White Bone", author: "Drake", type: "single", album: "HABIBTI" },
  { title: "Classic", author: "Drake", type: "single", album: "HABIBTI" },
  { title: "I’m Spent", author: "Drake & Loe Shimmy", type: "single", album: "HABIBTI" },
  { title: "High Fives", author: "Drake", type: "single", album: "HABIBTI" },
  { title: "Make Them Know", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Firm Friends", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Make Them Remember", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "2 Hard 4 The Radio", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Shabang", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Make Them Cry", author: "Drake", type: "single", album: "ICEMAN" },
  { title: "Stuck", author: "Drake", type: "single", album: "MAID OF HONOUR" },
  { title: "U Fancy ?", author: "Nine Vicious", type: "single" },
  { title: "ss", author: "Ken Carson", type: "single", album: "A Great Chaos (Deluxe)" },
  { title: "Tuition Remix", author: "Don Toliver & Lil Baby", type: "single" },
  { title: "real feel", author: "skaiwater", type: "single", album: "#gigi" },
  { title: "Violent Crimes", author: "Kanye West", type: "single", album: "ye" },
  { title: "Futura Free", author: "Frank Ocean", type: "single", album: "Blonde" },
  { title: "Walk In Wardrobe", author: "Central Cee", type: "single", album: "CAN'T RUSH GREATNESS" },
  { title: "Higher", author: "Tems", type: "single", album: "For Broken Ears" },
  { title: "GEEKIN", author: "Lil Yachty & Nemzzz", type: "single" },
  { title: "Wanna Be Startin' Somethin'", author: "Michael Jackson", type: "single", album: "Thriller" },
  { title: "Break My Heart (feat. Rick Ross)", author: "Estelle", type: "single", album: "All of Me" },
  { title: "Everyday Hustle", author: "Future, Metro Boomin & Rick Ross", type: "single", album: "WE DON'T TRUST YOU" },
  { title: "P.Y.T. (Pretty Young Thing)", author: "Michael Jackson", type: "single", album: "Thriller" },
  { title: "The Girl Is Mine (feat. Paul McCartney)", author: "Michael Jackson", type: "single", album: "The Indispensable Collection" },
  { title: "ATTENTION", author: "LAY LOE", type: "single" },
  { title: "SUPPOSED TO BE LOVED (feat. Lil Uzi Vert)", author: "DJ Khaled, Lil Baby & Future", type: "single" },
  { title: "Jumpman", author: "Drake & Future", type: "single", album: "What a Time To Be Alive" },
  { title: "Draco", author: "Future", type: "single", album: "FUTURE" },
  { title: "2005", author: "Ian", type: "album" },
  { title: "Versace (feat. Drake) [Remix]", author: "Migos", type: "single" },
  { title: "No New Friends (SFTB Remix) [feat. Drake, Rick Ross & Lil Wayne] [feat. Drake, Rick Ross & Lil Wayne]", author: "DJ Khaled", type: "single", album: "No New Friends (SFTB Remix) [feat. Drake, Rick Ross & Lil Wayne]" },
  { title: "24Hrs", author: "Nine Vicious", type: "single", album: "B4EM" },
  { title: "OH", author: "Kromow", type: "single" },
  { title: "Come Closer (feat. Drake)", author: "Wizkid", type: "single", album: "Sounds From the Other Side" },
  { title: "IF I WASN’T RAPPIN’", author: "Concrete Boys, Lil Yachty, Draft Day & Dc2trill", type: "single", album: "It's Us Vol. 2" },
  { title: "Jukebox Joints (feat. Joe Fox x Kanye West)", author: "A$AP Rocky", type: "single", album: "AT.LONG.LAST.A$AP" },
  { title: "9", author: "Dean Blunt & Panda Bear", type: "single", album: "ZUSHI" },
  { title: "Stars Align (with Drake)", author: "Majid Jordan & Drake", type: "single", album: "Wildest Dreams" },
  { title: "Views", author: "Drake", type: "album" },
  { title: "Jesus Is King", author: "Kanye West", type: "album" },
  { title: "baddie", author: "lostboyshawty", type: "single", album: "#b4BNS - EP" },
  { title: "meer dan dat", author: "lostboyshawty", type: "single", album: "#b4BNS - EP" },
  { title: "Round of Applause (feat. Drake)", author: "Waka Flocka Flame", type: "single" },
  { title: "Faithful (feat. Pimp C & dvsn)", author: "Drake", type: "single", album: "Views" },
  { title: "Another You (feat. Kanye West)", author: "The WRLDFMS Tony Williams", type: "single", album: "King or the Fool: An Opera, Vol. I" },
  { title: "Fear", author: "Drake", type: "single" },
  { title: "Silk Facë", author: "Yeat", type: "single", album: "ADL" },
  { title: "Don't Give It Away", author: "Fridayy & Chris Brown", type: "single", album: "Fridayy" },
  { title: "Sloppy Joe", author: "slayr", type: "single", album: "Half Blood" },
  { title: "35", author: "Kromow", type: "single" },
  { title: "Look At The Sky", author: "Kromow", type: "single", album: "35 NIGHTS" },
  { title: "Eyesight", author: "slayr", type: "single", album: "Half Blood (BloodLuxe)" },
  { title: "YSL Sweats", author: "Kromow & On The Radar", type: "single" },
  { title: "Love U Better (feat. Lil Wayne & the-Dream)", author: "Ty Dolla $ign", type: "single", album: "Beach House 3 (Deluxe)" },
  { title: "Don't Judge Me (feat. Future and Swae Lee)", author: "Ty Dolla $ign", type: "single", album: "Beach House 3 (Deluxe)" },
  { title: "Clout (feat. 21 Savage)", author: "Ty Dolla $ign", type: "single", album: "Beach House 3 (Deluxe)" },
  { title: "Amazing", author: "Nine Vicious", type: "single", album: "EMOTIONS" },
  { title: "Feedback", author: "Kanye West", type: "single", album: "The Life of Pablo" },
  { title: "3am", author: "Loe Shimmy & Don Toliver", type: "single", album: "Rockstar Junkie" },
  { title: "FEELINGS", author: "Central Cee", type: "single", album: "ALL ROADS LEAD HOME" },
  { title: "ATL (APPR3CIAT3 TH3 LOV3)", author: "Mike WiLL Made-It & 21 Savage", type: "single", album: "R3SET" },
  { title: "BEAUTY AND THE BEAST", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "PREACHER MAN", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "CIRCLES", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "WHITE LINES", author: "Kanye West & Andre Troutman", type: "single", album: "BULLY" },
  { title: "WHATEVER WORKS", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "PUNCH DRUNK", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "FATHER", author: "Kanye West & Travis Scott", type: "single", album: "BULLY" },
  { title: "THIS A MUST", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "KING", author: "Kanye West", type: "single", album: "BULLY" },
  { title: "Excavator", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "Housekeeping Knows (feat. Latto)", author: "Drake", type: "single", album: "100 GIGS" },
  { title: "Wheels Fall Off (feat. Kanye West)", author: "Ty Dolla $ign", type: "single" },
  { title: "Never Recover", author: "Lil Baby, Gunna & Drake", type: "single", album: "Drip Harder" },
  { title: "Mirror", author: "Kendrick Lamar", type: "single", album: "Mr. Morale & The Big Steppers" },
  { title: "CARXXX (feat. Idaly)", author: "Cho", type: "single", album: "GIOVANNI II" },
  { title: "R.I.P", author: "RainingLol", type: "single" },
  { title: "Set In Stone", author: "slayr", type: "single", album: "Half Blood" },
  { title: "Donda (Deluxe)", author: "Kanye West", type: "album" },
  { title: "Wat Een Tijd Om Te Leven", author: "Lil Kleine", type: "single", album: "Ibiza Stories" },
  { title: "I Feel It Coming (feat. Daft Punk)", author: "The Weeknd", type: "single", album: "Starboy (Deluxe)" },
  { title: "Balans", author: "Hef", type: "single", album: "Rook" },
  { title: "Let Me Love You", author: "Mario", type: "single", album: "Turning Point" },
  { title: "Thinkin Bout You", author: "Frank Ocean", type: "single", album: "channel ORANGE" },
  { title: "Break from Toronto", author: "PARTYNEXTDOOR", type: "single", album: "PARTYNEXTDOOR" },
  { title: "Madiba Riddim", author: "Drake", type: "single", album: "More Life" },
  { title: "Self Control", author: "Frank Ocean", type: "single", album: "Blonde" },
  { title: "miss u 2 (with Leon Thomas)", author: "Ty Dolla $ign", type: "single", album: "girl music vol. 1 - EP" },
  { title: "DMDD", author: "Marou & Massin", type: "single" },
  { title: "Alors on danse (feat. Kanye West) [feat. Kanye West]", author: "Stromae", type: "single", album: "Alors on danse - EP" },
  { title: "FORWARD", author: "SBTRKT & LEILAH", type: "single" },
  { title: "Scorpion", author: "Drake", type: "album" },
  { title: "F*****g Fans", author: "Drake", type: "single", album: "Certified Lover Boy" },
  { title: "Over", author: "R2Bees", type: "single", album: "Site 15" },
  { title: "I See Now (feat. Kanye West & Little Brother)", author: "Consequence", type: "single", album: "Take'Em To the Cleaners" },
  { title: "Workhardt Freestyle", author: "Nuez & Rio Da Yung Og", type: "single", album: "Life of a Yung Og" },
  { title: "ALL THE SAME", author: "Concrete Boys, Veeze & Lil Yachty", type: "single", album: "It's Us Vol. 2" },
  { title: "Pump Fake (feat. Playboi Carti)", author: "Ethereal", type: "single" },
  { title: "Murda", author: "Lil Yachty", type: "single" },
  { title: "Need for speed", author: "Lil Kleine", type: "single", album: "F*CK KLEINE" },
  { title: "Miley Cyrus", author: "Che", type: "single" },
  { title: "Search & Rescue", author: "Drake", type: "single" },
  { title: "fido", author: "deathtoricky", type: "single" },
  { title: "COPY, OK COOL", author: "Concrete Boys, Honest & Lil Yachty", type: "single", album: "It's Us Vol. 2" },
  { title: "Sere", author: "SPINALL & Fireboy DML", type: "single", album: "Grace" },
  { title: "STATS", author: "Baby Keem", type: "single", album: "DIE FOR MY BITCH" },
  { title: "Here I Am (feat. Nelly & Avery Storm)", author: "Rick Ross", type: "single", album: "Trilla (Bonus Track Version)" },
  { title: "Paranoid (feat. Destroy Lonely)", author: "Ken Carson", type: "single", album: "A Great Chaos (Deluxe)" },
  { title: "No Security", author: "Baby Keem", type: "single", album: "Ca$ino" },
  { title: "$ex Appeal (feat. Too $hort)", author: "Baby Keem", type: "single", album: "Ca$ino" },
  { title: "Birds & the Bees", author: "Baby Keem", type: "single", album: "Ca$ino" },
  { title: "GO (feat. Camo!, Dc2trill & Draft Day)", author: "PlaqueBoyMax, Concrete Boys & Lil Yachty", type: "single", album: "fivestarcrete - EP" },
  { title: "Run A Train", author: "J. Cole & Future", type: "single", album: "The Fall-Off" },
  { title: "Come Thru", author: "Drake", type: "single", album: "Nothing Was The Same (Deluxe)" },
  { title: "Yes You Can", author: "Young Thug", type: "single", album: "UY SCUTI (Supernova Edition)" },
  { title: "With Them", author: "Young Thug", type: "single", album: "Slime Season 3" },
  { title: "Groen Paars Yellow", author: "lostboyshawty", type: "single", album: "Jerragamo" },
  { title: "Hellcat Kenny (feat. Lil Uzi Vert)", author: "Young Thug", type: "single", album: "BUSINESS IS BUSINESS (Metro's Version)" },
  { title: "MILLIONAIRE", author: "Concrete Boys, Lil Yachty, Draft Day, Camo! & Dc2trill", type: "single", album: "It's Us Vol. 2" },
  { title: "9AM In Dallas", author: "Drake", type: "single" },
  { title: "Bij Zinnen", author: "Narco Polo, Willymakeamilli & Marou", type: "single" },
  { title: "Me Eige Beleid", author: "Marou, Massin & Chanou", type: "single" },
  { title: "Hoofd Teeh", author: "lostboyshawty", type: "single" },
  { title: "Bunce Road Blues", author: "J. Cole, Future & Tems", type: "single", album: "The Fall-Off" },
  { title: "About the Money (feat. Young Thug)", author: "T.I.", type: "single", album: "Paperwork (Deluxe)" },
  { title: "Body", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "E85", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "ATM", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "Call Back", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "Rendezvous (feat. Yeat)", author: "Don Toliver", type: "single", album: "OCTANE" },
  { title: "rodeo dr", author: "Gunna", type: "single", album: "a Gift & a Curse" },
  { title: "Denver", author: "Jack Harlow", type: "single", album: "Jackman." },
  { title: "Ambitious", author: "Jack Harlow", type: "single", album: "Jackman." },
  { title: "MARINATING", author: "DaBaby", type: "single", album: "BE MORE GRATEFUL" },
  { title: "CLEAR THIS SHIT", author: "DaBaby", type: "single", album: "BE MORE GRATEFUL" },
  { title: "OUT YA BUSINESS", author: "DaBaby", type: "single", album: "BE MORE GRATEFUL" },
  { title: "DON JULIO LEMONADE", author: "DaBaby", type: "single", album: "BE MORE GRATEFUL" },
  { title: "POP DAT THANG", author: "DaBaby", type: "single", album: "BE MORE GRATEFUL" },
  { title: "Family Ties", author: "Rick Ross", type: "single", album: "Hood Billionaire (Deluxe Version)" },
  { title: "The Weather (feat. Rick Ross & Cuzzy Capone)", author: "Nipsey Hussle", type: "single", album: "Crenshaw" },
  { title: "Sacrifices (feat. 2 Chainz & Young Thug)", author: "Drake", type: "single", album: "More Life" },
  { title: "Nothings Into Somethings", author: "Drake", type: "single", album: "More Life" },
  { title: "HALFTIME INTERLUDE", author: "21 Savage", type: "single", album: "WHAT HAPPENED TO THE STREETS?" },
  { title: "From Florida With Love", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Drew A Picasso", author: "Drake", type: "single", album: "For All The Dogs Scary Hours Edition" },
  { title: "The End", author: "Nine Vicious", type: "single", album: "FOR NOTHING" },
  { title: "Show Me a Good Time", author: "Drake", type: "single", album: "Thank Me Later" },
  { title: "Versace", author: "Westside Gunn", type: "single", album: "Pray for Paris" },
  { title: "Dbz", author: "Nine Vicious", type: "single", album: "FOR NOTHING" },
  { title: "HELICOPTER", author: "A$AP Rocky", type: "single", album: "Don't Be Dumb" },
  { title: "EAR BLEED", author: "Zukenee", type: "single" },
  { title: "2 Mazza (feat. Drake)", author: "Smiley & Drake", type: "single", album: "Don't Box Me In" },
  { title: "Best I Ever Had", author: "Drake", type: "single", album: "So Far Gone" },
  { title: "Successful (feat. Trey Songz & Lil Wayne)", author: "Drake", type: "single", album: "So Far Gone" },
  { title: "comethru (feat. kans)", author: "sor", type: "single", album: "INSOMNIA" },
  { title: "Ojuelegba (feat. Drake, Wizkid & Skepta) [Cadenza Remix] [Mixed]", author: "Wizkid", type: "single", album: "British Invasion (LargeUp Mix Series, Vol. 04) [DJ Mix]" },
  { title: "Diamonds & Dollars", author: "Dgtl", type: "single" },
  { title: "Look Alive (feat. Drake)", author: "BlocBoy JB", type: "single" },
  { title: "Can't Let Her Get Away", author: "Michael Jackson", type: "single", album: "Dangerous" },
  { title: "Remember the Time", author: "Michael Jackson", type: "single", album: "Dangerous" },
  { title: "(I Like) The Way You Love Me", author: "Michael Jackson", type: "single", album: "Michael" },
  { title: "Chicago", author: "Michael Jackson", type: "single", album: "XSCAPE (Deluxe)" },
  { title: "hoeveel is genoeg? (feat. ADF Samski)", author: "sor", type: "single" },
  { title: "I'm Sprung", author: "T-Pain", type: "single", album: "Rappa Ternt Sanga (Expanded Edition)" },
  { title: "Love Don't Live Here", author: "Meek Mill", type: "single", album: "Dreamchasers" },
  { title: "Place", author: "Playboi Carti", type: "single", album: "Whole Lotta Red" },
  { title: "Play Play (feat. Burna Boy)", author: "J Hus", type: "single", album: "Big Conspiracy" },
  { title: "Respect Ya Passion", author: "Nipsey Hussle", type: "single" },
  { title: "Denk Dat Ik Rijk Word", author: "Crooks & Hef", type: "single", album: "Freddy & Bundy" },
  { title: "Begraaf Me Als Een G", author: "Crooks & Hef", type: "single", album: "Freddy & Bundy" },
  { title: "WPFF", author: "Hef", type: "single", album: "Grijze" },
  { title: "Soldaten (skit)", author: "Hef", type: "single", album: "Grijze" },
  { title: "Smal (Interlude)", author: "Hef", type: "single", album: "Grijze" },
  { title: "Play Fair", author: "Kromow", type: "single" },
  { title: "Meh", author: "Playboi Carti", type: "single", album: "Whole Lotta Red" },
  { title: "SPREAD LIKE BUTTA", author: "Yakiyn", type: "single" },
  { title: "Not a Romantic", author: "Karri", type: "single", album: "Slider II" },
  { title: "the acronym", author: "Ken Carson & Destroy Lonely", type: "single" },
  { title: "B.M.F. (Blowin' Money Fast) [feat. Styles P]", author: "Rick Ross", type: "single", album: "Teflon Don" },
  { title: "ATLANTA TEARS", author: "21 Savage & Lil Baby", type: "single", album: "WHAT HAPPENED TO THE STREETS?" },
  { title: "MR RECOUP", author: "21 Savage & Drake", type: "single", album: "WHAT HAPPENED TO THE STREETS?" },
  { title: "RealSpill", author: "PlaqueBoyMax", type: "single", album: "Too Much Music-EP" },
  { title: "Cayendo (Sango Remix) [Mixed]", author: "Frank Ocean", type: "single", album: "Archive 001 (DJ Mix)" },
  { title: "How Far Will I Go (feat. Lil Yachty)", author: "Draft Day", type: "single" },
  { title: "Do2Much", author: "PlaqueBoyMax", type: "single", album: "Too Much Music-EP" },
  { title: "MalibuTides", author: "PlaqueBoyMax", type: "single", album: "Too Much Music-EP" },
  { title: "InTheMorning", author: "PlaqueBoyMax", type: "single", album: "Too Much Music-EP" },
  { title: "Different Music (Yerr On The Street Live Performance)", author: "Rio Da Yung Og & Yerr On The Street", type: "single" },
  { title: "Let’s Do It", author: "Lil Baby, Playboi Carti & Skooly", type: "single", album: "The Leaks" },
  { title: "The Resistance", author: "Drake", type: "single", album: "Thank Me Later" },
  { title: "Dave", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "from chi to saint mary", author: "millkzy", type: "single" },
  { title: "No Face", author: "Drake", type: "single" },
  { title: "Feds Did a Sweep", author: "Future", type: "single", album: "FUTURE" },
  { title: "Tuscan Leather", author: "Drake", type: "single", album: "Nothing Was The Same (Deluxe)" },
  { title: "Make a Mil", author: "PARTYNEXTDOOR", type: "single", album: "PARTYNEXTDOOR" },
  { title: "Yacht 2", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Me and Your Mama", author: "Childish Gambino", type: "single", album: "\"Awaken, My Love!\"" },
  { title: "Redbone", author: "Childish Gambino", type: "single", album: "\"Awaken, My Love!\"" },
  { title: "Nights", author: "Frank Ocean", type: "single", album: "Blonde" },
  { title: "Cameras / Good Ones Go Interlude", author: "Drake", type: "single", album: "Take Care (Deluxe Version)" },
  { title: "margiela", author: "Ken Carson", type: "single" },
  { title: "Poor Soul", author: "Dris", type: "single" },
  { title: "Crank Up Da Jet", author: "Loe Shimmy", type: "single" },
  { title: "When To Say When", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "III. Life: The Biggest Troll (Andrew Auernheimer)", author: "Childish Gambino", type: "single", album: "Because the Internet" },
  { title: "BABY I'M BACK", author: "The Kid LAROI", type: "single", album: "THE FIRST TIME (DELUXE VERSION)" },
  { title: "Oasis", author: "PlaqueBoyMax", type: "single" },
  { title: "Parking Lot", author: "Mustard & Travis Scott", type: "single" },
  { title: "Down Chick (feat. 3Three)", author: "YoungBoy Never Broke Again", type: "single", album: "38 Baby" },
  { title: "9", author: "Drake", type: "single", album: "Views" },
  { title: "i need u", author: "Ken Carson", type: "single", album: "A Great Chaos" },
  { title: "loading", author: "Ken Carson", type: "single", album: "A Great Chaos (Deluxe)" },
  { title: "yes", author: "Ken Carson", type: "single" },
  { title: "Soul Provider", author: "ian", type: "single", album: "2005" },
  { title: "History", author: "Dave & James Blake", type: "single", album: "The Boy Who Played the Harp" },
  { title: "Wish (Trippie Mix) [feat. Trippie Redd]", author: "Diplo", type: "single", album: "LIFE'S A TRIP" },
  { title: "What Do You Mean?", author: "Justin Bieber", type: "single", album: "Purpose (Deluxe)" },
  { title: "100 Grams", author: "Eem Triplin", type: "single", album: "Coming Undone" },
  { title: "Go Ian", author: "ian", type: "single", album: "2005" },
  { title: "Friends From Everywhere", author: "ian", type: "single", album: "2005" },
  { title: "You Told Me", author: "ian", type: "single", album: "2005" },
  { title: "Aw Shit", author: "ian", type: "single", album: "2005" },
  { title: "scars", author: "Baby Keem", type: "single", album: "The Melodic Blue (Deluxe)" },
  { title: "Green Room", author: "Ken Carson", type: "single", album: "A Great Chaos (Deluxe)" },
  { title: "And This is Just the Intro", author: "Tory Lanez", type: "single", album: "PLAYBOY" },
  { title: "her friends", author: "Nettspend", type: "single", album: "gone too soon" },
  { title: "From Time (feat. Jhené Aiko)", author: "Drake", type: "single", album: "Nothing Was The Same (Deluxe)" },
  { title: "Fight Night", author: "Migos", type: "single", album: "No Label II" },
  { title: "Billion Streams Freestyle", author: "Central Cee", type: "single", album: "Bolide Noir" },
  { title: "Solid (feat. Drake)", author: "Young Stoner Life, Young Thug & Gunna", type: "single", album: "Slime Language 2 (Deluxe)" },
  { title: "Shut Up", author: "Nettspend", type: "single", album: "BAD ASS F*CKING KID" },
  { title: "Paid the Fine (feat. Lil Baby & YTB Trench)", author: "Young Stoner Life, Young Thug & Gunna", type: "single", album: "Slime Language 2 (Deluxe)" },
  { title: "WHEN I THINK ABOUT IT", author: "Future", type: "single", album: "BEASTMODE 2" },
  { title: "Sticky", author: "Drake", type: "single", album: "Honestly, Nevermind" },
  { title: "RICK OWENS (feat. Ken Carson)", author: "Ufo361", type: "single", album: "SONY (Mixtape)" },
  { title: "Freestyle 3", author: "Ken Carson", type: "single", album: "XTENDED" },
  { title: "back of the club", author: "kwn", type: "single", album: "with all due respect" },
  { title: "Walk in the park", author: "Feng", type: "single" },
  { title: "Having Our Way (feat. Drake)", author: "Migos", type: "single", album: "Culture III" },
  { title: "WHERE DO YOU SLEEP?", author: "The Kid LAROI", type: "single", album: "THE FIRST TIME" },
  { title: "Maze", author: "Jimmy Q", type: "single", album: "Soulmetrics - Volume 1" },
  { title: "Stories About My Brother", author: "Drake", type: "single", album: "For All The Dogs Scary Hours Edition" },
  { title: "Nights Like This", author: "Future & Metro Boomin", type: "single", album: "WE STILL DON'T TRUST YOU" },
  { title: "All to Myself", author: "Future, Metro Boomin & The Weeknd", type: "single", album: "WE STILL DON'T TRUST YOU" },
  { title: "flex a band", author: "KD!", type: "single" },
  { title: "On The Radar Freestyle", author: "Drake & Central Cee", type: "single" },
  { title: "Figure It Out", author: "ian", type: "single" },
  { title: "Forever on Some Fly Shit", author: "Nipsey Hussle", type: "single", album: "TMC (Acapellas)" },
  { title: "WHAT A DAY", author: "Tyler, The Creator", type: "single", album: "CALL ME IF YOU GET LOST: The Estate Sale" },
  { title: "soooo high", author: "Destroy Lonely", type: "single", album: "</3³" },
  { title: "Elevate", author: "Drake", type: "single", album: "Scorpion" },
  { title: "I Ain't Coming Back", author: "ian", type: "single" },
  { title: "Can't Have Everything", author: "Drake", type: "single", album: "More Life" },
  { title: "Flexing All Summer", author: "Lackvill", type: "single" },
  { title: "Family Matters", author: "Drake", type: "single" },
  { title: "DOG HOUSE", author: "Drake, Julia Wolf & Yeat", type: "single" },
  { title: "Niagara Falls", author: "The Weeknd", type: "single", album: "Hurry Up Tomorrow" },
  { title: "Enjoy The Show", author: "The Weeknd & Future", type: "single", album: "Hurry Up Tomorrow" },
  { title: "Digital Dash", author: "Drake & Future", type: "single", album: "What a Time To Be Alive" },
  { title: "Red Flag (feat. ADF Ricky)", author: "ADF Samski", type: "single", album: "Cartier Music" },
  { title: "Banking On Me", author: "Gunna", type: "single" },
  { title: "Dark Fantasy", author: "Kanye West", type: "single", album: "My Beautiful Dark Twisted Fantasy" },
  { title: "8 Out Of 10", author: "Drake", type: "single", album: "Scorpion" },
  { title: "March 14", author: "Drake", type: "single", album: "Scorpion" },
  { title: "Feeeeeeeeel", author: "Cash Cobain", type: "single" },
  { title: "Beach leak", author: "Nettspend", type: "single", album: "BAD ASS F*CKING KID" },
  { title: "Sandra’s Rose", author: "Drake", type: "single", album: "Scorpion" },
  { title: "Don't Play (feat. The 1975 & Big Sean)", author: "Travis Scott", type: "single" },
  { title: "HOT UPTOWN (feat. Drake)", author: "Camila Cabello", type: "single", album: "C,XOXO" },
  { title: "Hours In Silence", author: "Drake & 21 Savage", type: "single", album: "Her Loss" },
  { title: "Peaches (feat. Daniel Caesar & GIVĒON)", author: "Justin Bieber", type: "single", album: "Justice" },
  { title: "5X", author: "Don Toliver", type: "single", album: "Life of a DON" },
  { title: "again", author: "Gunna", type: "single", album: "The Last Wun" },
  { title: "Ye", author: "Burna Boy", type: "single", album: "Outside" },
  { title: "Papi’s Home", author: "Drake", type: "single", album: "Certified Lover Boy" },
  { title: "Come to Life", author: "Kanye West", type: "single", album: "Donda" },
  { title: "War", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Oh U Went (feat. Drake)", author: "Young Thug", type: "single", album: "BUSINESS IS BUSINESS" },
  { title: "LORD LIFT ME UP", author: "Ye", type: "single", album: "DONDA 2" },
  { title: "JESSE", author: "Ye", type: "single", album: "DONDA 2" },
  { title: "No Hook II", author: "ADF Samski", type: "single", album: "Fresh Prince Van Noord" },
  { title: "Forever", author: "Drake, Kanye West, Lil Wayne & Eminem", type: "single" },
  { title: "Charged Up", author: "Drake", type: "single" },
  { title: "Back To Back", author: "Drake", type: "single" },
  { title: "Come and See Me", author: "PARTYNEXTDOOR & Drake", type: "single" },
  { title: "Two Birds, One Stone", author: "Drake", type: "single" },
  { title: "GLOCK", author: "Don Toliver", type: "single", album: "HARDSTONE PSYCHO" },
  { title: "Finished", author: "Bryson Tiller", type: "single", album: "Solace & The Vices" },
  { title: "Last Call", author: "Bryson Tiller", type: "single", album: "Solace & The Vices" },
  { title: "Which One", author: "Drake & Central Cee", type: "single" },
  { title: "i need meds", author: "Lil Yachty", type: "single" },
  { title: "fuck witcha boy", author: "Gunna", type: "single", album: "The Last Wun" },
  { title: "Chosen", author: "Jay Manwell", type: "single" },
  { title: "stephanie", author: "Eem Triplin", type: "single" },
  { title: "Dreams and Nightmares", author: "Meek Mill", type: "single", album: "Dreams and Nightmares (Deluxe Version)" },
  { title: "On Your Own", author: "Lil Tecca", type: "single", album: "DOPAMINE" },
  { title: "KICK OUT", author: "Travis Scott", type: "single", album: "JACKBOYS 2" },
  { title: "The Remorse", author: "Drake", type: "single", album: "Certified Lover Boy" },
  { title: "Miss Me (feat. Lil Wayne)", author: "Drake", type: "single", album: "Thank Me Later" },
  { title: "Fireworks (feat. Alicia Keys)", author: "Drake", type: "single", album: "Thank Me Later" },
  { title: "Irish Goodbye", author: "Lil Tecca", type: "single", album: "DOPAMINE" },
  { title: "NO COMMENTS", author: "Don Toliver", type: "single", album: "JACKBOYS 2" },
  { title: "Holy Vessel", author: "Nino Paid & Seddy Hendrinx", type: "single" },
  { title: "CHRISTIANS", author: "Yourboywonder", type: "single", album: "Before We Leave" },
  { title: "CHAMPAIN & VACAY", author: "Travis Scott & Don Toliver", type: "single", album: "JACKBOYS 2" },
  { title: "PBT", author: "Travis Scott, Tyla & Vybz Kartel", type: "single", album: "JACKBOYS 2" },
  { title: "Heat of the Moment", author: "Drake", type: "single", album: "Care Package" },
  { title: "Moeilijk", author: "Hef", type: "single", album: "Hefvermogen 2" },
  { title: "Super Wrong", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "What Did I Miss?", author: "Drake", type: "single" },
  { title: "Circo Loco", author: "Drake & 21 Savage", type: "single", album: "Her Loss" },
  { title: "Jenni", author: "Cash Cobain & Chow Lee", type: "single", album: "2 Slizzy 2 Sexy (Deluxe)" },
  { title: "Jholiday 2", author: "Cash Cobain & Chow Lee", type: "single", album: "2 Slizzy 2 Sexy (Deluxe)" },
  { title: "Blakk Rokkstar", author: "Ken Carson", type: "single", album: "More Chaos" },
  { title: "bankroll", author: "DDG", type: "single", album: "blame the chat" },
  { title: "no help", author: "DDG", type: "single", album: "blame the chat" },
  { title: "Apple Pie", author: "Travis Scott", type: "single", album: "Rodeo" },
  { title: "pick up the phone (feat. Quavo)", author: "Young Thug & Travis Scott", type: "single", album: "Birds In The Trap Sing McKnight" },
  { title: "sweet sweet", author: "Travis Scott", type: "single", album: "Birds In The Trap Sing McKnight" },
  { title: "Shut It Down", author: "ian", type: "single" },
  { title: "Swag 2", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Casper", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "East Coast N*gga", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "SOS", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Pink Moscato", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Paid For", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Sevan", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Yacht", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Yellow Lamb Truck", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "2016", author: "PlaqueBoyMax", type: "single", album: "Five Forever (Deluxe)" },
  { title: "Love All (feat. JAŸ-Z)", author: "Drake", type: "single", album: "Certified Lover Boy" },
  { title: "Champions", author: "Kanye West, Gucci Mane, Big Sean, 2 Chainz, Travis Scott, Yo Gotti, Quavo & Desiigner", type: "single" },
  { title: "Pon Road (feat. Sevn Alias)", author: "SFB", type: "single", album: "77 Nachten" },
  { title: "ETA", author: "TopKid! Archive", type: "single" },
  { title: "FELLOFF 2 (feat. Plaqueboymax)", author: "Prince Ji", type: "single" },
  { title: "Zeven", author: "Hef", type: "single", album: "Bloed Is Dikker Dan Water" },
  { title: "Welcome 2 Da City", author: "Thirteendegrees °", type: "single", album: "Clique City Vol. 2" },
  { title: "Da Problem Solva", author: "Thirteendegrees °", type: "single", album: "Clique City Vol. 2" },
  { title: "Alright", author: "Kent Jones", type: "single" },
  { title: "WORTH IT", author: "Offset & Don Toliver", type: "single", album: "SET IT OFF (Versions)" },
  { title: "Champagne", author: "Nino Paid", type: "single" },
  { title: "Cooln", author: "Nino Paid, BabyChiefDoit & PlaqueBoyMax", type: "single", album: "Love Me As I Am" },
  { title: "Ain't No Switch", author: "Jripey & 5ive", type: "single", album: "Euphoria" },
  { title: "High Fashion (feat. Mustard)", author: "Roddy Ricch", type: "single", album: "Please Excuse Me For Being Antisocial" },
  { title: "Get To It (feat. Nino Paid)", author: "ian", type: "single" },
  { title: "LOYAL (feat. Drake)", author: "PARTYNEXTDOOR", type: "single", album: "PARTYMOBILE (Chopped Not Slopped)" },
  { title: "Kennedy", author: "lostboyshawty", type: "single" },
  { title: "We Major (feat. Nas & Really Doe)", author: "Kanye West", type: "single", album: "Late Registration" },
  { title: "YSL (feat. Playboi Carti)", author: "Gunna", type: "single", album: "Drip Season 2" },
  { title: "Tree On The Hill (Lunch Break Freestyle)", author: "Lyrical Lemonade & Nino Paid", type: "single" },
  { title: "Pack It Up", author: "ian", type: "single" },
  { title: "Out thë way", author: "Yeat", type: "single", album: "Lyfë" },
  { title: "Zo Zijn", author: "sor", type: "single", album: "Bae Doven" },
  { title: "This Ain’t What You Wanted", author: "sor", type: "single", album: "Bae Doven" },
  { title: "Under Ground Kings", author: "Drake", type: "single", album: "Take Care (Deluxe Version)" },
  { title: "Play No Games (feat. Chris Brown & Ty Dolla $ign)", author: "Big Sean", type: "single", album: "Dark Sky Paradise (Deluxe)" },
  { title: "Lord Knows (feat. Rick Ross)", author: "Drake", type: "single", album: "Take Care (Deluxe Version)" },
  { title: "The Ride", author: "Drake", type: "single", album: "Take Care (Deluxe Version)" },
  { title: "Diamonds Dancing (feat. Travis Scott)", author: "Young Stoner Life, Young Thug & Gunna", type: "single", album: "Slime Language 2" },
  { title: "Jodeci Freestyle (feat. J. Cole)", author: "Drake", type: "single", album: "Care Package" },
  { title: "Draft Day", author: "Drake", type: "single", album: "Care Package" },
  { title: "Over My Dead Body", author: "Drake", type: "single", album: "Take Care (Deluxe Version)" },
  { title: "Bane", author: "Destroy Lonely", type: "single" },
  { title: "NOSTYLIST", author: "Destroy Lonely", type: "single", album: "NO STYLIST" },
  { title: "Losses", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Pain 1993 (feat. Playboi Carti)", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Toosie Slide", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Chicago Freestyle", author: "Drake & GIVĒON", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Know Yourself", author: "Drake", type: "single", album: "If You're Reading This It's Too Late" },
  { title: "Energy", author: "Drake", type: "single", album: "If You're Reading This It's Too Late" },
  { title: "Jungle", author: "Drake", type: "single", album: "If You're Reading This It's Too Late" },
  { title: "You & The 6", author: "Drake", type: "single", album: "If You're Reading This It's Too Late" },
  { title: "Desires (feat. Future)", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Outstanding Member", author: "Ronnie Flex", type: "single", album: "SDL 1" },
  { title: "Free Mind", author: "Tems", type: "single", album: "For Broken Ears" },
  { title: "Piece of My Heart (feat. Brent Faiyaz)", author: "Wizkid", type: "single", album: "Morayo" },
  { title: "My Shayla * SPICE-RILLA", author: "Tory Lanez & Dstny", type: "single", album: "PETERSON" },
  { title: "VTMNTSCOAT", author: "Destroy Lonely", type: "single", album: "NO STYLIST" },
  { title: "Went Thru It", author: "Young Thug", type: "single", album: "BUSINESS IS BUSINESS" },
  { title: "Bacc Seat (feat. Ty Dolla $ign)", author: "Roddy Ricch", type: "single", album: "Please Excuse Me For Being Antisocial" },
  { title: "TURNINUP", author: "Destroy Lonely", type: "single", album: "NO STYLIST" },
  { title: "Down Below", author: "Roddy Ricch", type: "single", album: "Feed Tha Streets ll" },
  { title: "Can't Tell Me Nothing", author: "Kanye West", type: "single", album: "Graduation" },
  { title: "CN TOWER", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "CELIBACY", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "PIMMIE'S DILEMMA", author: "Pimmie, PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "GIMME A HUG", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "GREEDY", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "WHEN HE'S GONE", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "GLORIOUS", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "OMW", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "SOMEBODY LOVES ME", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "DIE TRYING", author: "PARTYNEXTDOOR, Drake & Yebba", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "RAINING IN HOUSTON", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "DEEPER", author: "PARTYNEXTDOOR", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "CRYING IN CHANEL", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "SOMETHING ABOUT YOU", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "MOTH BALLS", author: "PARTYNEXTDOOR & Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "NOKIA", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "BRIAN STEEL", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "SMALL TOWN FAME", author: "Drake", type: "single", album: "$ome $exy $ongs 4 U" },
  { title: "Mask Off", author: "Future", type: "single", album: "FUTURE" },
  { title: "311", author: "Jordan Ward & Gwen Bunn", type: "single", album: "FORWARD" },
  { title: "Man Of The Year", author: "PlaqueBoyMax, UnoTheActivist & 5STAR", type: "single" },
  { title: "AWKWARD FREESTYLE", author: "Eem Triplin", type: "single" },
  { title: "PRICETAG/BEVERLYWOOD", author: "Jordan Ward & Lido", type: "single", album: "moreward(FORWARD)" },
  { title: "Through the Fire", author: "Deca OTA", type: "single" },
  { title: "BUBBLE GUM", author: "Quavo", type: "single", album: "QUAVO HUNCHO" },
  { title: "Focused (feat. Young Thug)", author: "Quavo", type: "single", album: "Rocket Power" },
  { title: "Pipe Down", author: "Drake", type: "single", album: "Certified Lover Boy" },
  { title: "Millions", author: "Young Thug", type: "single", album: "So Much Fun (Deluxe)" },
  { title: "Monëy so big", author: "Yeat", type: "single", album: "Up 2 Më" },
  { title: "way back", author: "Travis Scott", type: "single", album: "Birds In The Trap Sing McKnight" },
  { title: "CAROUSEL", author: "Travis Scott", type: "single", album: "ASTROWORLD" },
  { title: "DrIP DrIp Drip (feat. Meek Mill)", author: "Tory Lanez", type: "single", album: "LoVE me NOw (ReLoAdeD)" },
  { title: "WHAT TO DO? (feat. Don Toliver)", author: "JACKBOYS & Travis Scott", type: "single", album: "JACKBOYS" },
  { title: "Backyard", author: "Travis Scott", type: "single", album: "DAYS BEFORE RODEO" },
  { title: "Deceiving Eve", author: "Tory Lanez", type: "single", album: "PLAYBOY" },
  { title: "Come Through and Chill (feat. J. Cole & Salaam Remi)", author: "Miguel", type: "single", album: "War & Leisure" },
  { title: "Heartless", author: "The Weeknd", type: "single", album: "After Hours (Deluxe Video Album)" },
  { title: "Swangin' On Westheimer", author: "Don Toliver", type: "single", album: "Life of a DON" },
  { title: "Come and See Me", author: "PARTYNEXTDOOR & Drake", type: "single", album: "PARTYNEXTDOOR 3 (P3)" },
  { title: "530", author: "¥$, Kanye West & Ty Dolla $ign", type: "single", album: "VULTURES 2" },
  { title: "Down In Atlanta", author: "Pharrell Williams & Travis Scott", type: "single" },
  { title: "BË QUIET", author: "Yeat & Kodak Black", type: "single", album: "LYFESTYLE" },
  { title: "LYFE PARTY", author: "Yeat", type: "single", album: "LYFESTYLE" },
  { title: "Blow for Blow (feat. J. Cole)", author: "Tee Grizzley", type: "single" },
  { title: "Used to This (feat. Drake)", author: "Future", type: "single", album: "FUTURE" },
  { title: "Nothing Like Your Exes", author: "Ty Dolla $ign", type: "single", album: "Featuring Ty Dolla $ign" },
  { title: "Privileged Rappers", author: "Drake & 21 Savage", type: "single", album: "Her Loss" },
  { title: "F.N", author: "Lil Tjay", type: "single", album: "True 2 Myself" },
  { title: "Leaked", author: "Lil Tjay", type: "single" },
  { title: "Crooked Smile (feat. TLC)", author: "J. Cole", type: "single", album: "Born Sinner (Deluxe Version)" },
  { title: "All To Me", author: "GIVĒON", type: "single", album: "When It's All Said And Done... Take Time" },
  { title: "today i did good", author: "Gunna", type: "single", album: "One of Wun" },
  { title: "Away From Home", author: "Drake", type: "single", album: "For All The Dogs" },
  { title: "8am in Charlotte", author: "Drake", type: "single", album: "For All The Dogs" },
  { title: "All The Parties (feat. Chief Keef)", author: "Drake", type: "single", album: "For All The Dogs" },
  { title: "Drew A Picasso", author: "Drake", type: "single", album: "For All The Dogs" },
  { title: "Bam (feat. Damian \"Jr. Gong\" Marley)", author: "JAY-Z", type: "single", album: "4:44" },
  { title: "4:44", author: "JAY-Z", type: "single" },
  { title: "Otis (feat. Otis Redding)", author: "JAŸ-Z & Kanye West", type: "single", album: "Watch the Throne (Deluxe)" },
  { title: "Champion", author: "Kanye West", type: "single", album: "Graduation" },
  { title: "Welcome to the Jungle", author: "JAŸ-Z & Kanye West", type: "single", album: "Watch the Throne (Deluxe)" },
  { title: "That's My Bitch", author: "JAŸ-Z & Kanye West", type: "single", album: "Watch the Throne (Deluxe)" },
  { title: "New Day", author: "JAŸ-Z & Kanye West", type: "single", album: "Watch the Throne (Deluxe)" },
  { title: "Landed", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Lo Mein", author: "Lil Uzi Vert", type: "single", album: "Eternal Atake (Deluxe) - LUV vs. The World 2" },
  { title: "Not You Too (feat. Chris Brown)", author: "Drake", type: "single", album: "Dark Lane Demo Tapes" },
  { title: "Family Feud (feat. Beyoncé)", author: "JAY-Z", type: "single", album: "4:44" },
  { title: "One Time (feat. Future)", author: "NAV & Don Toliver", type: "single", album: "Demons Protected By Angels (Bonus Version)" },
  { title: "My Friends (feat. Lil Durk)", author: "Ty Dolla $ign & Mustard", type: "single" },
  { title: "Parade on Cleveland (feat. Drake)", author: "Young Thug", type: "single", album: "BUSINESS IS BUSINESS" },
  { title: "Late", author: "Kanye West", type: "single", album: "Late Registration" },
  { title: "No Thank You", author: "Bryson Tiller", type: "single", album: "Bryson Tiller" },
  { title: "Number", author: "Ty Dolla $ign", type: "single", album: "Beach House 3 (Deluxe)" },
  { title: "White Dress", author: "Kanye West", type: "single", album: "The Man with the Iron Fists" },
  { title: "WASTING TIME (feat. Drake & The Neptunes)", author: "Brent Faiyaz", type: "single", album: "WASTELAND" },
  { title: "Childs Play", author: "Drake", type: "single", album: "Views" },
  { title: "ALL MINE", author: "Brent Faiyaz", type: "single", album: "WASTELAND" },
  { title: "The Take (feat. Chris Brown)", author: "Tory Lanez", type: "single", album: "Chixtape 5" },
  { title: "ATTITUDE (FEAT. CHARLIE WILSON & CASH COBAIN)", author: "Don Toliver", type: "single", album: "HARDSTONE PSYCHO" },
  { title: "the ends", author: "Travis Scott", type: "single", album: "Birds In The Trap Sing McKnight" },
  { title: "All Day (feat. Theophilus London, Allan Kingdom & Paul McCartney)", author: "Kanye West", type: "single" },
  { title: "act ii: date @ 8 (remix)", author: "4batz & Drake", type: "single" },
  { title: "Had Enough (feat. Offset & Quavo)", author: "Don Toliver", type: "single", album: "Heaven Or Hell" },
  { title: "God Is", author: "Kanye West", type: "single", album: "JESUS IS KING" },
  { title: "BURN", author: "¥$, Kanye West & Ty Dolla $ign", type: "single", album: "VULTURES 1" },
  { title: "No More Parties in LA", author: "Kanye West", type: "single", album: "The Life of Pablo" },
  { title: "Follow God", author: "Kanye West", type: "single", album: "JESUS IS KING" },
  { title: "Selah", author: "Kanye West", type: "single", album: "JESUS IS KING" },
  { title: "How Bout Now", author: "Drake", type: "single", album: "Care Package" },
  { title: "With You (feat. PARTYNEXTDOOR)", author: "Drake", type: "single", album: "Views" },
  { title: "Can You Stand the Rain", author: "New Edition", type: "single" },
  { title: "The College Dropout", author: "Kanye West", type: "album" },
  { title: "Uuugly", author: "Drake", type: "single" },
  { title: "Xscape", author: "Michael Jackson", type: "album" },
  { title: "DONDA 2", author: "Kanye West", type: "album" },
  { title: "HIM ALL ALONG", author: "Gunna", type: "single" },
  { title: "back in the a", author: "Gunna", type: "single" },
  { title: "Blue Green Red", author: "Drake", type: "single", album: "No Face", unreleased: true },
];
