/**
 * Generates static SiteX route files for blog posts and supply products.
 */
import fs from "node:fs";
import path from "node:path";
import { getAllPostSlugs } from "../src/lib/blog";
import { getCachedPublishedProducts } from "../src/lib/supply-products";

const WRITING_DIR = path.join(process.cwd(), "src/pages/writing");
const SUPPLY_DIR = path.join(process.cwd(), "src/pages/supply");

function sanitizeFileSegment(value: string) {
  return value.replace(/[^a-zA-Z0-9._-]/g, "-");
}

function cleanDir(dir: string) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}

function writeWritingPostPage(slug: string) {
  const file = path.join(WRITING_DIR, `${sanitizeFileSegment(slug)}.tsx`);
  const content = `// Auto-generated by scripts/generate-pages.ts
import BaseLayout from "@/components/layouts/base";
import ClientShell from "@/components/layouts/client-shell";
import WritingPostPage from "@/components/pages/writing-post-page";
import { getPostBySlug } from "@/lib/blog";

export default async function Page() {
  const post = await getPostBySlug(${JSON.stringify(slug)});

  return (
    <BaseLayout title={post.title} description={post.description} pathname={${JSON.stringify(`/writing/${slug}`)}} noIndex={post.draft}>
      <ClientShell client:load pathname={${JSON.stringify(`/writing/${slug}`)}}>
        <WritingPostPage post={post} />
      </ClientShell>
    </BaseLayout>
  );
}
`;
  fs.writeFileSync(file, content);
}

function writeSupplyProductPage(productId: string) {
  const file = path.join(SUPPLY_DIR, `${sanitizeFileSegment(productId)}.tsx`);
  const content = `// Auto-generated by scripts/generate-pages.ts
import BaseLayout from "@/components/layouts/base";
import ClientShell from "@/components/layouts/client-shell";
import SupplyProductPage from "@/components/pages/supply-product-page";
import { loadSupplyProductPage } from "@/lib/supply-product-page";

export default async function Page() {
  const data = await loadSupplyProductPage(${JSON.stringify(productId)});

  if (!data) {
    return (
      <BaseLayout title="Product Not Found" pathname={${JSON.stringify(`/supply/${productId}`)}}>
        <ClientShell client:load pathname={${JSON.stringify(`/supply/${productId}`)}}>
          <section className="text-[17px]">
            <h1 className="text-2xl font-semibold">Product not found</h1>
            <p className="text-muted-foreground mt-2">
              <a href="/supply" className="underline">
                Back to Supply
              </a>
            </p>
          </section>
        </ClientShell>
      </BaseLayout>
    );
  }

  const productIcon = data.product.images[0]?.src ?? data.defaultImage ?? undefined;

  return (
    <BaseLayout
      title={data.product.title}
      description={data.product.description.replace(/<[^>]*>/g, "").slice(0, 160)}
      pathname={${JSON.stringify(`/supply/${productId}`)}}
      icon={productIcon}
    >
      <ClientShell client:load pathname={${JSON.stringify(`/supply/${productId}`)}}>
        <SupplyProductPage {...data} />
      </ClientShell>
    </BaseLayout>
  );
}
`;
  fs.writeFileSync(file, content);
}

async function main() {
  cleanDir(WRITING_DIR);
  cleanDir(SUPPLY_DIR);

  const slugs = getAllPostSlugs();
  for (const slug of slugs) {
    writeWritingPostPage(slug);
  }
  console.log(`Generated ${slugs.length} writing route(s)`);

  const products = getCachedPublishedProducts();
  for (const product of products) {
    writeSupplyProductPage(product.id);
  }
  const productCount = products.length;
  console.log(`Generated ${productCount} supply product route(s)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
